"""Dempwolf v2 SPICE subcircuit generators + fit-and-export pipeline.

Generates 3-pin triode and 4-pin pentode subcircuits using the
Dempwolf Extended v2 model:
  - Koren-style softplus normalized cathode emission
  - arctan-based current splitting (Ia / Ig2)
  - Optional secondary emission (sigma > 0)
  - Region-A correction for triodes (Va/sqrt(Kvb_t+Va^2))
"""

from __future__ import annotations

import logging
from typing import Dict, List

import numpy as np

from lm19.spice_export._common import SpiceFitResult
from lm19.constants import (
    TOPOLOGY_PENTODE,
    TOPOLOGY_TRIODE,
    TOPOLOGY_TRIODE_CONNECTED,
)

log = logging.getLogger(__name__)


def _generate_dempwolf_pentode_subcircuit(
    safe_name, tube_type, dp,
    rms_error, max_error, n_points, ig2_rms=None,
    ref=None,
    mfg_date: str = "",
):
    """Generate Dempwolf v2 pentode SPICE subcircuit text.

    Uses Koren-style normalized cathode emission for pentodes,
    arctan-based current splitting, and optional secondary emission.

    Pin order: Anode, Grid1, Cathode, Grid2 (A G K G2).
    """
    has_sec = dp.sigma > 0

    lines = []
    lines.append(f"; SPICE model for {tube_type}")
    if mfg_date:
        lines.append(f"; Manufactured: {mfg_date}")
    lines.append("; Generated by LM19 Tube Tester")
    lines.append("; Dempwolf Extended v2 pentode model")
    if ref and ref.source:
        lines.append(f"; Reference data source: {ref.source}")
    if rms_error is not None:  # absent for exported-from-model .subs
        lines.append(f"; Fit quality (Ia): RMS = {rms_error:.2f} mA, "
                     f"Max = {max_error:.2f} mA")
        if ig2_rms is not None:
            lines.append(f"; Fit quality (Ig2): RMS = {ig2_rms:.2f} mA")
        lines.append(f"; Data points used: {n_points}")
    lines.append(";")
    lines.append(f";   mu    = {dp.mu:.4f}      ; amplification factor")
    lines.append(f";   G     = {dp.G:.6e}  ; cathode emission scale")
    lines.append(f";   gamma = {dp.gamma:.4f}      ; emission exponent")
    lines.append(f";   C     = {dp.C:.4f}      ; softplus scale")
    lines.append(f";   Gg    = {dp.Gg:.6e}  ; grid emission scale")
    lines.append(f";   xi    = {dp.xi:.4f}      ; grid current exponent")
    lines.append(f";   Cg    = {dp.Cg:.4f}      ; grid damping")
    lines.append(f";   Kvb   = {dp.Kvb:.4f}     ; knee base voltage")
    lines.append(f";   Kvb1  = {dp.Kvb1:.4f}     ; knee voltage slope")
    lines.append(f";   Kn    = {dp.Kn:.4f}      ; knee exponent")
    lines.append(f";   fg2   = {dp.fg2:.6f}    ; screen interception")
    lines.append(f";   A     = {dp.A:.6e}  ; Durchgriff")
    if has_sec:
        lines.append(f";   sigma = {dp.sigma:.4f}     ; sec. emission yield")
        lines.append(f";   Ks    = {dp.Ks:.4f}      ; sec. emission shape")
        lines.append(f";   lam   = {dp.lam:.4f}")
        lines.append(f";   nu    = {dp.nu:.4f}")
        lines.append(f";   w     = {dp.w:.4f}")
    lines.append(";")
    lines.append("; Ik = G * softplus(C*(1/mu + Vg1/Vg2))^gamma * (1 + A*Va)")
    lines.append("; alpha = (1-fg2) * (2/pi) * arctan((Va/Kvb_eff)^Kn)")
    lines.append("; Ia = Ik * alpha    (grid current handled by D3 diode)")
    lines.append("; Ig2 = Ik * (1 - alpha)")
    lines.append("; Pin order: Anode, Grid1, Cathode, Grid2")
    lines.append(";")

    _TWO_OVER_PI = 2.0 / np.pi

    lines.append(f".SUBCKT {safe_name} A G K G2")
    params1 = (f"+ PARAMS: MU={dp.mu:.4f} G={dp.G:.6e} "
               f"GAMMA={dp.gamma:.4f} C={dp.C:.4f}")
    lines.append(params1)
    params2 = (f"+ KVB={dp.Kvb:.4f} KVB1={dp.Kvb1:.4f} "
               f"KN={dp.Kn:.4f} FG2={dp.fg2:.6f} A={dp.A:.6e}")
    lines.append(params2)
    params4 = f"+ TWOPI={_TWO_OVER_PI:.10f}"
    lines.append(params4)

    if has_sec:
        params5 = (f"+ SIGMA={dp.sigma:.4f} KS={dp.Ks:.4f} "
                   f"LAM={dp.lam:.4f} NU={dp.nu:.4f} W={dp.w:.4f}")
        lines.append(params5)

    caps = ref.caps if ref and ref.caps else None
    rgi = ref.rgi if ref and ref.rgi else 2000
    if caps:
        lines.append(f"+ CCG1={caps.ccg1}P CCG2={caps.ccg2}P "
                      f"CPG1={caps.cpg1}P CG1G2={caps.cg1g2}P "
                      f"CCP={caps.ccp}P RGI={rgi}")
    else:
        lines.append(f"+ CCG1=0.0P CCG2=0.0P CPG1=0.0P CG1G2=0.0P "
                      f"CCP=0.0P RGI={rgi}")

    lines.append("*")

    # E1: softplus cathode intermediate (Koren-style normalized)
    # softplus = (Vg2/C) * ln(1 + exp(C * (1/mu + Vg1/Vg2)))
    # MIN(...,700) mirrors Python _EXP_CLIP: exp overflow guard only —
    # unreachable for physical params, keeps LTspice finite on transients.
    lines.append("RE1 7 0 1MEG")
    lines.append("E1 7 0 VALUE=")
    lines.append("+{V(G2,K)/C*LOG(1+EXP(MIN("
                 "C*(1/MU+V(G,K)/MAX(V(G2,K),0.01)),700)))}")

    # E2: cathode emission current Ik = G * E1^gamma * (1 + A*Va)
    lines.append("E2 8 0 VALUE=")
    lines.append("+{G*(PWR(MAX(V(7),0),GAMMA))*(1+A*MAX(V(A,K),0.01))}")
    lines.append("RE2 8 0 1MEG")

    # E4: effective Kvb = max(Kvb + Kvb1 * max(Vg2/mu + Vg1, 0), 0.1)
    lines.append("E4 10 0 VALUE=")
    lines.append("+{MAX(KVB+KVB1*MAX(V(G2,K)/MU+V(G,K),0),0.1)}")
    lines.append("RE4 10 0 1MEG")

    # E5: alpha = (1-fg2) * (2/pi) * arctan((Va/Kvb_eff)^Kn)
    lines.append("E5 11 0 VALUE=")
    lines.append("+{(1-FG2)*TWOPI*ATAN(PWR(MAX(V(A,K),0.01)/V(10),KN))}")
    lines.append("RE5 11 0 1MEG")

    # G1/G2: current splitting — Ia = Ik * alpha, Ig2 = Ik * (1 - alpha)
    if has_sec:
        # With secondary emission
        # Vco = Vg2/lam - nu*Vg1 - w
        # x = max(1 - Va/Vco, 0)
        # Isec = sigma * Ik * (Va/Vg2) * x * exp(-Ks * x)
        lines.append("E6 12 0 VALUE=")
        lines.append("+{MAX(V(G2,K)/LAM-NU*V(G,K)-W,0.01)}")
        lines.append("RE6 12 0 1MEG")
        lines.append("G1 A K VALUE=")
        lines.append("+{V(8)*V(11)"
                      "-SIGMA*V(8)*(MAX(V(A,K),0.01)/MAX(V(G2,K),0.01))"
                      "*MAX(1-MAX(V(A,K),0.01)/V(12),0)"
                      "*EXP(-KS*MAX(1-MAX(V(A,K),0.01)/V(12),0))}")
        lines.append("G2 G2 K VALUE=")
        lines.append("+{V(8)*(1-V(11))"
                      "+SIGMA*V(8)*(MAX(V(A,K),0.01)/MAX(V(G2,K),0.01))"
                      "*MAX(1-MAX(V(A,K),0.01)/V(12),0)"
                      "*EXP(-KS*MAX(1-MAX(V(A,K),0.01)/V(12),0))}")
    else:
        lines.append("G1 A K VALUE={V(8)*V(11)}")
        lines.append("G2 G2 K VALUE={V(8)*(1-V(11))}")

    lines.append("RCP A K 1G")
    lines.append("*")
    lines.append("C1 G K {CCG1}    ; cathode-grid1")
    lines.append("C4 G2 K {CCG2}    ; cathode-grid2")
    lines.append("C5 G2 G {CG1G2}   ; grid1-grid2")
    lines.append("C2 A G {CPG1}    ; grid1-plate")
    lines.append("C3 A K {CCP}     ; cathode-plate")
    lines.append("*")
    lines.append("R1 G 5 {RGI}     ; grid current")
    lines.append("D3 5 K DX")
    lines.append(".MODEL DX D(IS=1N RS=1 CJO=10PF TT=1N)")
    lines.append("*")
    lines.append(f".ENDS {safe_name}")
    lines.append("")
    return "\n".join(lines)


def _generate_dempwolf_triode_subcircuit(
    safe_name, tube_type, dp,
    rms_error, max_error, n_points,
    ref=None,
    mfg_date: str = "",
):
    """Generate Dempwolf v2 triode SPICE subcircuit text.

    Pin order: Anode, Grid, Cathode.
    """
    lines = []
    lines.append(f"; SPICE model for {tube_type}")
    if mfg_date:
        lines.append(f"; Manufactured: {mfg_date}")
    lines.append("; Generated by LM19 Tube Tester")
    lines.append("; Dempwolf Extended v2 triode model")
    if ref and ref.source:
        lines.append(f"; Reference data source: {ref.source}")
    if rms_error is not None:  # absent for exported-from-model .subs
        lines.append(f"; Fit quality: RMS error = {rms_error:.2f} mA, "
                     f"Max error = {max_error:.2f} mA")
        lines.append(f"; Data points used: {n_points}")
    lines.append(";")
    lines.append(f";   mu    = {dp.mu:.4f}")
    lines.append(f";   G     = {dp.G:.6e}")
    lines.append(f";   gamma = {dp.gamma:.4f}")
    lines.append(f";   C     = {dp.C:.4f}")
    lines.append(f";   Kvb_t = {dp.Kvb_t:.4f}")
    lines.append(";")
    lines.append("; sp = ln(1 + exp(C*(Va/mu + Vg1))) / C")
    lines.append("; Ia = G * sp^gamma  (Region A: Vg1 scaled by Va/sqrt(Kvb_t+Va^2))")
    lines.append("; Pin order: Anode, Grid, Cathode")
    lines.append(";")

    lines.append(f".SUBCKT {safe_name} A G K")
    lines.append(f"+ PARAMS: MU={dp.mu:.4f} G={dp.G:.6e} "
                 f"GAMMA={dp.gamma:.4f} C={dp.C:.4f} "
                 f"KVBT={dp.Kvb_t:.4f}")

    caps = ref.caps if ref and ref.caps else None
    rgi = ref.rgi if ref and ref.rgi else 2000
    if caps:
        lines.append(f"+ CCG={caps.ccg}P CGP={caps.cgp}P "
                      f"CCP={caps.ccp}P RGI={rgi}")
    else:
        lines.append(f"+ CCG=0.0P CGP=0.0P CCP=0.0P RGI={rgi}")

    lines.append("*")
    # Vg_eff = Vg1 * Va / sqrt(Kvb_t + Va^2)  (Region A correction)
    # sp = ln(1 + exp(C * (Va/mu + Vg_eff))) / C
    # Ia = G * max(sp, 0)^gamma
    # MIN(...,700) mirrors Python _EXP_CLIP (exp overflow guard only).
    lines.append("E1 7 0 VALUE=")
    lines.append("+{LOG(1+EXP(MIN(C*(V(A,K)/MU+V(G,K)*V(A,K)"
                 "/SQRT(KVBT+V(A,K)*V(A,K))),700)))/C}")
    lines.append("RE1 7 0 1G")
    lines.append("G1 A K VALUE={G*(PWR(MAX(V(7),0),GAMMA))}")
    lines.append("RCP A K 1G")

    if caps:
        lines.append("*")
        lines.append(f"C1 G K {{CCG}}    ; cathode-grid  ({caps.ccg} pF)")
        lines.append(f"C2 G A {{CGP}}    ; grid-plate    ({caps.cgp} pF)")
        lines.append(f"C3 A K {{CCP}}    ; cathode-plate ({caps.ccp} pF)")

    lines.append("*")
    lines.append(f"R1 G 5 {{RGI}}    ; grid stopper ({rgi} ohm)")
    lines.append("D3 5 K DX")
    lines.append(".MODEL DX D(IS=1N RS=1 CJO=10PF TT=1N)")
    lines.append("*")
    lines.append(f".ENDS {safe_name}")
    lines.append("")
    return "\n".join(lines)


def fit_and_export_dempwolf(
    path: str,
    tube_type: str,
    safe_name: str,
    points: List[Dict],
    ref,
    topology: str,
    backend: str,
    mfg_date: str = "",
) -> SpiceFitResult:
    """Fit Dempwolf model and write .sub file."""
    from lm19.dempwolf import fit_dempwolf

    result = fit_dempwolf(points, topology)
    dp = result.model.dempwolf

    effective_topo = (TOPOLOGY_TRIODE if topology == TOPOLOGY_TRIODE_CONNECTED
                      else topology)

    if effective_topo == TOPOLOGY_PENTODE:
        content = _generate_dempwolf_pentode_subcircuit(
            safe_name, tube_type, dp,
            result.rms_error, result.max_error, result.n_points,
            ig2_rms=result.rms_ig2, ref=ref, mfg_date=mfg_date)
    else:
        content = _generate_dempwolf_triode_subcircuit(
            safe_name, tube_type, dp,
            result.rms_error, result.max_error, result.n_points,
            ref=ref, mfg_date=mfg_date)

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    return SpiceFitResult(
        model_type=effective_topo,
        algorithm="dempwolf",
        params=result.params,
        rms_error=result.rms_error,
        max_error=result.max_error,
        n_points=result.n_points,
        path=path,
    )
