"""Reefman (Derk / DerkE) SPICE subcircuit generator + fit-and-export.

Compatible with the TubeLib.inc convention: all splitting factors and
derived constants are pre-computed in Python and emitted as .PARAM
values, so the resulting subcircuit needs no symbolic helper macros.

Variants supported (driven by ``rp.type``):
  - ``Penthode``      — basic Derk pentode
  - ``PenthodeDE``    — Derk-E (exponential splitting)
  - ``PenthodeVD``    — Derk variable-mu
  - ``PenthodeVDE``   — Derk-E variable-mu
  - ``BTetrodeD``     — beam tetrode with secondary emission
  - ``BTetrodeDE``    — Derk-E beam tetrode with secondary emission

Pin order: Anode, Grid1, Cathode, Grid2 (A G K G2).
"""

from __future__ import annotations

import logging
from typing import Dict, List

from lm19.spice_export._common import SpiceFitResult
from lm19.constants import (
    TOPOLOGY_PENTODE,
)

log = logging.getLogger(__name__)


def _generate_reefman_subcircuit(
    safe_name, tube_type, rp,
    rms_error, max_error, n_points, ig2_rms=None,
    ref=None,
    mfg_date: str = "",
):
    """Generate Reefman (Derk/DerkE) SPICE subcircuit text.

    Compatible with TubeLib.inc format. All splitting parameters
    are precomputed and passed as SPICE .PARAM values.

    Pin order: Anode, Grid1, Cathode, Grid2 (A G K G2).
    """
    # Derived SPICE parameters (precomputed, as in TubeLib.inc)
    alpha = 1.0 - (rp.kg1 / rp.kg2) * (1.0 + rp.als)
    ookg1_m_ookg2 = 1.0 / rp.kg1 - 1.0 / rp.kg2
    aokg1 = rp.A / rp.kg1
    alkg1_p_alskg2 = alpha / rp.kg1 + rp.als / rp.kg2

    is_de = rp.type in ("BTetrodeDE", "PenthodeDE", "PenthodeVDE")
    is_bt = rp.type in ("BTetrodeD", "BTetrodeDE")
    is_vmu = rp.type in ("PenthodeVD", "PenthodeVDE")
    variant_label = "DerkE" if is_de else "Derk"

    lines = []
    lines.append(f"; SPICE model for {tube_type}")
    if mfg_date:
        lines.append(f"; Manufactured: {mfg_date}")
    lines.append("; Generated by LM19 Tube Tester")
    lines.append(f"; Reefman {variant_label} model ({rp.type})")
    if ref and ref.source:
        lines.append(f"; Reference data source: {ref.source}")
    if rms_error is not None:  # absent for exported-from-model .subs
        lines.append(f"; Fit quality (Ia): RMS = {rms_error:.2f} mA, "
                     f"Max = {max_error:.2f} mA")
        if ig2_rms is not None:
            lines.append(f"; Fit quality (Ig2): RMS = {ig2_rms:.2f} mA")
        lines.append(f"; Data points used: {n_points}")
    lines.append(";")
    lines.append(f";   MU    = {rp.mu:.4f}")
    lines.append(f";   EX    = {rp.ex:.4f}")
    lines.append(f";   Kg1   = {rp.kg1:.4f}")
    lines.append(f";   Kg2   = {rp.kg2:.4f}")
    lines.append(f";   KP    = {rp.kp:.4f}")
    lines.append(f";   KVB   = {rp.kvb:.4f}")
    lines.append(f";   als   = {rp.als:.4f}    ; alpha_s")
    lines.append(f";   be    = {rp.be:.6f}    ; beta")
    lines.append(f";   A     = {rp.A:.6e}    ; Durchgriff")
    if is_bt:
        lines.append(f";   Sc    = {rp.Sc:.4e}    ; secondary emission")
        lines.append(f";   ap    = {rp.ap:.4f}")
        lines.append(f";   w     = {rp.w:.2f}")
        lines.append(f";   nu    = {rp.nu:.4f}")
        lines.append(f";   lam   = {rp.lam:.4f}")
    if is_vmu:
        lines.append(f";   MUb   = {rp.mu_b:.4f}    ; variable-mu section B")
        lines.append(f";   EXb   = {rp.ex_b:.4f}")
        lines.append(f";   svar  = {rp.svar:.4f}")
    lines.append(";")
    lines.append(f"; Derived: alpha = {alpha:.6f}")
    lines.append(f";   Ookg1mOokG2   = {ookg1_m_ookg2:.6e}")
    lines.append(f";   Aokg1         = {aokg1:.6e}")
    lines.append(f";   alkg1palskg2  = {alkg1_p_alskg2:.6e}")
    lines.append(";")

    if is_de:
        lines.append("; Splitting: DerkE — f(Va) = exp(-(be*Va)^1.5)")
    else:
        lines.append("; Splitting: Derk  — f(Va) = 1 / (1 + be*Va)")
    lines.append("; Ia = Ip * (Ookg1mOokG2 + Aokg1*Va - alkg1palskg2*f(Va))")
    lines.append("; Ig2 = Ip/Kg2 * (1 + als*f(Va))")
    lines.append("; Pin order: Anode, Grid1, Cathode, Grid2")
    lines.append(";")

    lines.append(f".SUBCKT {safe_name} A G K G2")

    params_parts = [
        f"MU={rp.mu:.4f}", f"EX={rp.ex:.4f}",
        f"KG1={rp.kg1:.4f}", f"KG2={rp.kg2:.4f}",
        f"KP={rp.kp:.4f}", f"KVB={rp.kvb:.4f}",
    ]
    lines.append(f"+ PARAMS: {' '.join(params_parts)}")

    derived_parts = [
        f"Ookg1mOokG2={ookg1_m_ookg2:.6e}",
        f"Aokg1={aokg1:.6e}",
        f"alkg1palskg2={alkg1_p_alskg2:.6e}",
        f"be={rp.be:.6f}",
        f"als={rp.als:.6f}",
    ]
    lines.append(f"+ {' '.join(derived_parts)}")

    if is_bt:
        sec_parts = [
            f"Sc={rp.Sc:.4e}", f"ap={rp.ap:.6f}",
            f"w={rp.w:.4f}", f"nu={rp.nu:.4f}",
            f"lam={rp.lam:.4f}",
        ]
        lines.append(f"+ {' '.join(sec_parts)}")

    if is_vmu:
        vmu_parts = [
            f"MUb={rp.mu_b:.4f}", f"EXb={rp.ex_b:.4f}",
            f"svar={rp.svar:.4f}",
        ]
        lines.append(f"+ {' '.join(vmu_parts)}")

    caps = ref.caps if ref and ref.caps else None
    rgi = ref.rgi if ref and ref.rgi else 2000
    if caps:
        lines.append(f"+ CCG1={caps.ccg1}P CCG2={caps.ccg2}P "
                      f"CPG1={caps.cpg1}P CG1G2={caps.cg1g2}P "
                      f"CCP={caps.ccp}P RGI={rgi}")
    else:
        lines.append(f"+ CCG1=0.0P CCG2=0.0P CPG1=0.0P CG1G2=0.0P "
                      f"CCP=0.0P RGI={rgi}")

    lines.append("*")

    # E1: cathode current intermediate voltage
    # MIN(...,700) mirrors Python _EXP_CLIP (exp overflow guard only).
    lines.append("RE1 7 0 1MEG")
    lines.append("E1 7 0 VALUE=")
    lines.append("+{V(G2,K)/KP*LOG(1+EXP(MIN(KP*(1/MU"
                 "+V(G,K)/SQRT(KVB+V(G2,K)*V(G2,K))),700)))}")

    if is_vmu:
        lines.append("RE11 17 0 1MEG")
        lines.append("E11 17 0 VALUE=")
        lines.append("+{V(G2,K)/KP*LOG(1+EXP(MIN(KP*(1/MUb"
                     "+V(G,K)/SQRT(KVB+V(G2,K)*V(G2,K))),700)))}")
        lines.append("E20 9 0 VALUE = "
                      "{(1-svar)*0.5*(PWR(V(7),EX)+PWRS(V(7),EX))"
                      "+ svar*0.5*(PWR(V(17),EXb)+PWRS(V(17),EXb))}")

    # E2: splitting factor
    if is_de:
        lines.append("E2 8 0 VALUE = "
                      "{Ookg1mOokG2 + Aokg1*V(A,K)"
                      " - alkg1palskg2*Exp(-be*V(A,K)*SQRT(be*V(A,K)))}")
    else:
        lines.append("E2 8 0 VALUE = "
                      "{Ookg1mOokG2 + Aokg1*V(A,K)"
                      " - alkg1palskg2/(1 + be*V(A,K))}")

    if is_bt:
        lines.append("E3 9 0 VALUE = "
                      "{Sc/kG2*V(A,K)*(1+tanh(-ap*(V(A,K)-V(G2,K)/lam+w+nu*V(G,K))))}")

    if is_vmu:
        # Variable-mu: Ip is in node 9 from E20
        if is_bt:
            lines.append("G1 A K VALUE = {V(9)*(V(8)-V(9))}")
        else:
            lines.append("G1 A K VALUE = {V(9)*V(8)}")
        if is_de:
            lines.append("G2 G2 K VALUE = "
                          "{V(9)/KG2*(1+als*Exp(-be*V(A,K)*SQRT(be*V(A,K))))}")
        else:
            lines.append("G2 G2 K VALUE = "
                          "{V(9)/KG2*(1+als/(1+be*V(A,K)))}")
    else:
        ip_expr = "0.5*(PWR(V(7),EX)+PWRS(V(7),EX))"
        if is_bt:
            lines.append(f"G1 A K VALUE = {{{ip_expr}*(V(8)-V(9))}}")
        else:
            lines.append(f"G1 A K VALUE = {{{ip_expr}*V(8)}}")
        # Theory.pdf eq. (43)/(45): secondary emission arrives at the
        # screen (+Ip*Psec, node 9). NB TubeLib.inc omits this term in its
        # G2 sources (library diverges from the paper) — LM19 follows the
        # paper, keeping Ia+Ig2 independent of Sc.
        psec_term = f"+{ip_expr}*V(9)" if is_bt else ""
        if is_de:
            lines.append(f"G2 G2 K VALUE = "
                          f"{{{ip_expr}/KG2*(1+als*Exp(-be*V(A,K)*SQRT(be*V(A,K)))){psec_term}}}")
        else:
            lines.append(f"G2 G2 K VALUE = "
                          f"{{{ip_expr}/KG2*(1+als/(1+be*V(A,K))){psec_term}}}")

    lines.append("RCP A K 1G")
    lines.append("*")

    lines.append("C1 G K {CCG1}    ; cathode-grid1")
    lines.append("C4 G2 K {CCG2}    ; cathode-grid2")
    lines.append("C5 G2 G {CG1G2}   ; grid1-grid2")
    lines.append("C2 A G {CPG1}    ; grid1-plate")
    lines.append("C3 A K {CCP}     ; cathode-plate")
    lines.append("*")
    lines.append("R1 G 5 {RGI}     ; grid current")
    lines.append("D3 5 K DX")
    lines.append(".MODEL DX D(IS=1N RS=1 CJO=10PF TT=1N)")
    lines.append("*")
    lines.append(f".ENDS {safe_name}")
    lines.append("")
    return "\n".join(lines)


def fit_and_export_reefman(
    path: str,
    tube_type: str,
    safe_name: str,
    points: List[Dict],
    ref,
    backend: str,
    mfg_date: str = "",
) -> SpiceFitResult:
    """Fit Reefman model and write .sub file."""
    from lm19.reefman import fit_reefman

    result = fit_reefman(points, TOPOLOGY_PENTODE)
    rp = result.model.reefman

    content = _generate_reefman_subcircuit(
        safe_name, tube_type, rp,
        result.rms_error, result.max_error, result.n_points,
        ig2_rms=result.rms_ig2, ref=ref, mfg_date=mfg_date)

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    return SpiceFitResult(
        model_type=TOPOLOGY_PENTODE,
        algorithm="reefman",
        params=result.params,
        rms_error=result.rms_error,
        max_error=result.max_error,
        n_points=result.n_points,
        path=path,
    )
